### ISSUE TITLE
remove sketch result

### ISSUE THREAD

**Issue by zhaozeliu** [KoslickiLab/frac-kmc#5] opened 2024-12-06 10:05 UTC
Hello,

When  I run fracKmcSketch <infilename> <outfilename> [options]  like this, it always create  mkdir ./EiacCvC8If   and finally remove that. I can not get the output sketch file to use for sourmash. If I miss some parameter ? 

Thanks.

**Comment by mahmudhera** [comment] 2024-12-06 13:04
Can you kindly share the output sketch file, and/or the error(s) you get when you try to use it with sourmash?

**Comment by zhaozeliu** [comment] 2024-12-06 17:00
Sorry about the confusion.  When I run command:
fracKmcSketch 2-46290674_S239_L004_R1_001.fastq 2_sketch --ksize 21 --scaled 1000 --seed 42 --n 32 --fq

the result show:


mkdir ./EiacCvC8If
frackmc -ci1 -cs35565 -scaled1000 -S42 -k21 -t32 -fq 2-46290674_S239_L004_R1_001.fastq 2-46290674_S239_L004_R1_001.fastq_kmers_EiacCvC8If ./EiacCvC8If
**********************
Stage 1: 100%
Stage 2: 100%
KMC 1st stage: 23.0826s
KMC 2nd stage: 10.0768s
Total    : 33.1594s
Tmp size : 377MB

Stats:
   No. of k-mers above FMH. threshold :    177828929
   No. of unique k-mers               :    178006902
   No. of k-mers in FMH. sketch       :       177973
   Total no. of k-mers                :    307858782
frackmcdump -ci1 -scaled1000 -S42 -ksize21 -filename2-46290674_S239_L004_R1_001.fastq 2-46290674_S239_L004_R1_001.fastq_kmers_EiacCvC8If 2_sketch
Output abundances 0
rm 2-46290674_S239_L004_R1_001.fastq_kmers_EiacCvC8If*
rm -r ./EiacCvC8If

I expect the output file will be some sketch file that I can use for other tools like sourmash, but I didn't see any in output path, also I see " rm 2-46290674_S239_L004_R1_001.fastq_kmers_EiacCvC8If*  rm -r ./EiacCvC8If ". Is that mean it create a tem dir and removes the result file? I see in your main introduction page the command like this: fracKmcSketch <fasta> <sketch_name> --ksize 21 --scaled 1000 --seed 42 --n 32 --fa   I thought the output file should be <sketch_name>   Am I wrong?

Thanks

**Comment by mahmudhera** [comment] 2024-12-06 17:12
Is a file named "2_sketch" generated? What is the content in that file?

**Comment by zhaozeliu** [comment] 2024-12-06 17:46
no, that was what I expected but I didn't see output file "2_sketch". I tried a few times for different fastq file and different output name or path. But didn't see any output anywhere. I see anytime this will generate a "mkdir ./EiacCvC8If" like this to do calculation, but in the end it always been removed in the end of process like "rm 2-46290674_S239_L004_R1_001.fastq_kmers_EiacCvC8If*  rm -r ./EiacCvC8If", I asked some AI tools it said it might be the problem.
I don't know if I am correct but I didn't see any other parameter in --help about this. I was expecting this command will generate sketch file then could be use in sourmash. 

Thanks.

**Comment by mahmudhera** [comment] 2024-12-06 18:02
The directory thats being generated and removed is just a temporary directory, it shouldn’t contain the output file. Its used to store the KMC binary database. Let me check things on my end and see if I can recreate the issue. Is there a way to upload the fastq file so I can test on it?

**Comment by mahmudhera** [comment] 2024-12-06 20:36
I am not exactly able to recreate the issue, things are working for me. I am attaching a fastq file, the sketch generated by frac_kmc, and the sketch generated by sourmash sketch. You may need to unzip first.
[SRS047708-fastq-and-sketches.zip](https://github.com/user-attachments/files/18043474/SRS047708-fastq-and-sketches.zip)

Command used to create sketch using sourmash:
```
sourmash compute -k 21 --scaled 1000 --dna --seed 42 -o SRS047708.fastq_sourmash_sketch SRS047708.fastq
```

Command used to create sketch using frac_kmc:
```
fracKmcSketch SRS047708.fastq SRS047708_frackmc_sketch --ksize 21 --scaled 1000 --seed 42 --n 32 --fq
```

Can you test with these files to see if they work for you?

Also, did you download the pre-built executables or did you use make to build the binaries on your system?

**Comment by zhaozeliu** [comment] 2024-12-06 22:07
Thank you so much, it works when use your file and my single file. However when I run for two fastq file(for same individual), it doesn't generate sketch file.

fracKmcSketch 1-46918254_S308_L004_R1_001.fastq 1-46918254_S308_L004_R2_001.fastq 1_sketch --ksize 21 --scaled 1000 --seed 42 --n 32 --fq  

Do I miss something here ?

**Comment by mahmudhera** [comment] 2024-12-06 23:34
I don’t understand, how could you use two files when the program is expecting a single file as input? The first argument you give is the input fasta/fastq file, the next argument is the output file.

You would need to provide a single file as input. If you want a single combined sketch for both these fastq files, you can concatenate them and run the program.

As the program works fine for a single file (as is the intended behavior), I am closing the issue. Feel free to reopen it if the problem persists for a single input file.

**Closed as completed by mahmudhera** 2024-12-06 23:34 UTC

**Comment by zhaozeliu** [comment] 2024-12-07 03:20
Thank you so much, I thought it could use two inputs like other tools such as mash.  Now I know it, I will concatenate first. Thanks for your help.

**Comment by mahmudhera** [comment] 2024-12-07 05:06
Understandable. Let me see if we can add the functionality of providing two paired end read files to the program. If we do add the functionality, I will let you know! Thank you!
